'use client';
import { useEffect, useState } from 'react';
import NeuralCanvas from '@/components/NeuralCanvas';
import NewsCard from '@/async/NewsCard';

export default function NeuroFluxHome() {
  const [news, setNews] = useState<any[]>([]);

  useEffect(() => {
    const fetchPulse = async () => {
      try {
        // In production, this points to the public/feed.json generated by engine
        const res = await fetch('/feed.json');
        const data = await res.json();
        setNews(data);
      } catch (e) { console.error("Signal Lost", e); }
    };
    fetchPulse();
    const interval = setInterval(fetchPulse, 300000); // 5 min refresh
    return () => clearInterval(interval);
  }, []);

  return (
    <main className="relative min-h-screen text-white bg-black overflow-hidden">
      <NeuralCanvas />
      <div className="relative z-10 pt-24 px-6 max-w-3xl mx-auto pointer-events-none">
        <div className="mb-12 space-y-2">
          <h1 className="text-6xl font-black tracking-tighter text-cyan-400 italic uppercase">NEUROFLUX</h1>
          <p className="text-pink-500 font-mono animate-pulse text-xs tracking-[0.3em]">SYSTEM_STATUS: ACTIVE_STREAM</p>
        </div>

        <div className="space-	y-6 h-[60vh] overflow-y-auto pr-4 custom-scrollbar pointer-events-auto">
          {news.length > 0 ? (
            news.map((item) => <NewsCard key={item.id} {...item} />)
          ) : (
            <div className="text-cyan-900 font-mono animate-pulse text-sm">SCANNING_FOR_SIGNALS...</div>
          )}
        </div>
      </div>

      {/* CRT Scanline Overlay */}
      <div className="pointer-events-none fixed inset-0 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_4px,3px_100%] z-50 opacity-30"></div>
    </main>
  );
}